name: Actualizar dashboard Google Sheets

on:
  schedule:
    - cron: '0 * * * *'  # Cada hora
  workflow_dispatch:     # También puede ejecutarse manualmente

jobs:
  run_r_scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar librerías necesarias
        run: |
          Rscript -e 'install.packages("pacman")'
          Rscript -e 'pacman::p_load(dplyr, gt, googledrive, gtsummary, googlesheets4, ggplot2, httr, haven, jsonlite, kableExtra, labelled, lubridate, purrr, skimr, stringr, tidyverse, tidyr, tidygeocoder, readxl, writexl)'

      - name: Ejecutar script 0_Importar_datos
        run: Rscript 0_Importar_datos.R

      - name: Ejecutar script 1_Auditoria
        run: Rscript 1_Auditoria.R

      - name: Ejecutar script 2_Labels
        run: Rscript 2_Labels.R

      - name: Ejecutar script 3_Monitoreo
        run: Rscript 3_Monitoreo.R
