name: Run R Scripts Hourly

# Este flujo de trabajo se ejecutará cada hora
on:
  schedule:
    - cron: "0 * * * *" # Cada hora en el minuto 0
  workflow_dispatch: # Permite ejecutarlo manualmente desde la interfaz de GitHub

jobs:
  run-r-scripts:
    name: Execute R Scripts Hourly
    runs-on: ubuntu-latest

    steps:
      # Configurar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar R en el entorno
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.4.3 # Cambia esto si necesitas otra versión de R

      # Instalar las librerías necesarias
      - name: Install R libraries
        run: |
          Rscript -e 'install.packages("pacman")'
          Rscript -e 'pacman::p_load(tidyverse, httr, jsonlite, googledrive, writexl, haven, stringr, labelled, lubridate, gtsummary, googlesheets4)'

      # Ejecutar Script 0_Importar_datos
      - name: Run Script 0_Importar_datos
        run: Rscript 0_Importar_datos.R

      # Ejecutar Script 1_Auditoria
      - name: Run Script 1_Auditoria
        run: Rscript 1_Auditoria.R

      # Ejecutar Script 2_Labels
      - name: Run Script 2_Labels
        run: Rscript 2_Labels.R

      # Ejecutar Script 3_Monitoreo
      - name: Run Script 3_Monitoreo
        run: Rscript 3_Monitoreo.R
