name: Run R Scripts Hourly

on:
  schedule:
    - cron: "0 * * * *" # Cada hora
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  run-r-scripts:
    name: Execute R Scripts Hourly
    runs-on: ubuntu-latest

    steps:
      # Configurar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Instalar dependencias del sistema operativo
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libxml2-dev libharfbuzz-dev libfribidi-dev
          sudo apt-get install -y libgdal-dev libgeos-dev libproj-dev # Dependencias para sf

      # Configurar R en el entorno
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.4.3 # Cambia esto si necesitas otra versión de R

      # Instalar las librerías necesarias
      - name: Install R libraries
        run: |
          Rscript -e 'install.packages("pacman")'
          Rscript -e 'pacman::p_load(tidyverse, httr, jsonlite, googledrive, writexl, haven, stringr, labelled, lubridate, gtsummary, googlesheets4, kableExtra, skimr, tidygeocoder, sf)'

      # Ejecutar scripts en orden
      - name: Run Script 0_Importar_datos
        run: Rscript 0_Importar_datos.R

      - name: Run Script 1_Auditoria
        run: Rscript 1_Auditoria.R

      - name: Run Script 2_Labels
        run: Rscript 2_Labels.R
